---
- hosts: all
  become: yes
  tasks:
    - name: check docker --version
      ansible.builtin.command:
        docker --version
      ignore_errors: yes
      register: output
      
    - ansible.builtin.debug:
        var: output


...